
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  date date,
  type text,
  message text,
  status text default 'pending'
);

-- Allow public to insert bookings (anyone can book)
alter table public.bookings enable row level security;

create policy "Allow public inserts"
on public.bookings for insert
to public
with check (true);

-- Allow admin (authenticated) to view bookings
create policy "Allow admin select"
on public.bookings for select
to authenticated
using (true);
